version: '3'
services:
  php:
    image: my-php-app
    ports:
      - "8081:80"
    volumes:
      - ./php/www:/var/www/html
  db:
    image: mysql/mysql-server:latest
    environment: 
      MYSQL_ROOT_PASSWORD: kal5088
    ports:
      - "3306:3306"
      - "33060:33060"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
